
title: Serge Prokofiev Archive as Data
tag: A Digital Humanities Project
email: ne99@columbia.edu m.saccomano@columbia.edu
description: Visualizations and data files drawn the from Serge Prokofiev Archive finding aid.

# ! ! -- BASEURL SETTINGS -- ! !

baseurl: "/spademo"
#baseurl: ""

url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  mss2221

# BUILD SETTINGS
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed

collections:
    verovio:
      output: true
      permalink: /verovio/:path/


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
